In [2]:
import numpy as np

In [17]:
students = np.array(["Harsh", "Laukik", "Utkarsh", "Aditya", "Dishant","Shiva"])

marks = np.array([
    [85, 90, 78, 92, 88],
    [70, 75, 80, 72, 68],
    [95, 98, 94, 97, 96],
    [60, 65, 58, 62, 64],
    [88, 84, 91, 87, 90],
    [45,50,45,35,25]
])

print("Students:")
print(students)

print("\nMarks:")
print(marks)

Students:
['Harsh' 'Laukik' 'Utkarsh' 'Aditya' 'Dishant' 'Shiva']

Marks:
[[85 90 78 92 88]
 [70 75 80 72 68]
 [95 98 94 97 96]
 [60 65 58 62 64]
 [88 84 91 87 90]
 [45 50 45 35 25]]


In [18]:
avg = np.mean(marks, axis=1)

print("\nAverage Marks:")
for i in range(len(students)):
    print(students[i], ":", avg[i])


Average Marks:
Harsh : 86.6
Laukik : 73.0
Utkarsh : 96.0
Aditya : 61.8
Dishant : 88.0
Shiva : 40.0


In [19]:
print("\nHighest and Lowest Marks:")
for i in range(len(students)):
    print(students[i], "Highest =", np.max(marks[i]), "Lowest =", np.min(marks[i]))


Highest and Lowest Marks:
Harsh Highest = 92 Lowest = 78
Laukik Highest = 80 Lowest = 68
Utkarsh Highest = 98 Lowest = 94
Aditya Highest = 65 Lowest = 58
Dishant Highest = 91 Lowest = 84
Shiva Highest = 50 Lowest = 25


In [29]:
print("\nStandard Deviation:")
for i in range(len(students)):
    print(students[i], ":", round(np.std(marks[i]), 2))


Standard Deviation:
Harsh : 4.88
Laukik : 4.2
Utkarsh : 1.41
Aditya : 2.56
Dishant : 2.45
Shiva : 8.94


In [24]:
rank = np.argsort(avg)[::-1]

print("\nRanking:")
for i in rank:
    print(students[i], ":", avg[i])


Ranking:
Utkarsh : 96.0
Dishant : 88.0
Harsh : 86.6
Laukik : 73.0
Aditya : 61.8
Shiva : 40.0


In [25]:
class_avg = np.mean(avg)

print("\nClass Average =", class_avg)

print("\nStudents Above Class Average:")
for i in range(len(students)):
    if avg[i] > class_avg:
        print(students[i])
        


Class Average = 74.23333333333333

Students Above Class Average:
Harsh
Utkarsh
Dishant


In [26]:
subject_avg = np.mean(marks, axis=0)

print("\nSubject-wise Average:")
for i in range(len(subject_avg)):
    print("Subject", i + 1, ":", subject_avg[i])


Subject-wise Average:
Subject 1 : 73.83333333333333
Subject 2 : 77.0
Subject 3 : 74.33333333333333
Subject 4 : 74.16666666666667
Subject 5 : 71.83333333333333


In [14]:
percentage = np.sum(marks, axis=1) / 5

print("\nPercentage:")
for i in range(len(students)):
    print(students[i], ":", percentage[i], "%")


Percentage:
Harsh : 86.6 %
Laukik : 73.0 %
Utkarsh : 96.0 %
Aditya : 61.8 %
Dishant : 88.0 %


In [27]:
labels = students
values = percentage

print("\nVisualization Ready Data")
print("Labels:", labels)
print("Values:", values)


Visualization Ready Data
Labels: ['Harsh' 'Laukik' 'Utkarsh' 'Aditya' 'Dishant' 'Shiva']
Values: [86.6 73.  96.  61.8 88. ]
