In [1]:
import numpy as np
print(np.__version__)

2.2.2


In [4]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a)
print(type(a))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
<class 'numpy.ndarray'>


In [7]:
a = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[5,11,55,1,6],[5,8,1,8,1]]])
print(a)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[ 5 11 55  1  6]
  [ 5  8  1  8  1]]]


In [8]:
d = np.zeros((2,3))
print(d)

[[0. 0. 0.]
 [0. 0. 0.]]


In [9]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [10]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
2
6
int64


In [13]:
a = np.arange(12)
print(a)
b = a.reshape(3,4)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [18]:
a = np.array([10,15,30,45, 45])
b = np.array([5,6,70,60,50])

print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a == b)
print(a > b)

[ 15  21 100 105  95]
[  5   9 -40 -15  -5]
[  50   90 2100 2700 2250]
[2.         2.5        0.42857143 0.75       0.9       ]
[False False False False False]
[ True  True False False False]


In [19]:
a = np.array([10,20,30,40,50])
print(a[0])
print(a[3])

b = np.array([[1,2,3],[4,5,6]])
print(b[1,2])

10
40
6


In [20]:
a = np.array([10,15,20,25,30])
mask = a > 18
print(a[mask])

[20 25 30]


In [29]:
print(np.sum(a))
print(np.mean(a))
print(np.mean(a))
print(np.std(a))
print(np.var(a))
print(np.min(a))
print(np.max(a))

100
20.0
20.0
7.0710678118654755
50.0
10
30


In [32]:
a = np.arange(9)
print(a)
print(np.split(a,9))

[0 1 2 3 4 5 6 7 8]
[array([0]), array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([7]), array([8])]
